
# ========= Border =========
file_panel_border = '#383835'
sidebar_border = '#383835'
footer_border = '#383835'

# ========= Border Active =========
file_panel_border_active = '#DE6A41'
sidebar_border_active = '#DE6A41'
footer_border_active = '#DE6A41'
modal_border_active = '#DE6A41'

# ========= Background (bg) =========
full_screen_bg = '#d0d0c8'
file_panel_bg = '#d0d0c8'
sidebar_bg = '#d0d0c8'
footer_bg = '#d0d0c8'
modal_bg = '#d0d0c8'

# ========= Foreground (fg) =========
full_screen_fg = '#242424'
file_panel_fg = '#242424'
sidebar_fg = '#242424'
footer_fg = '#242424'
modal_fg = '#242424'

# ========= Special Color =========
cursor = '#242424'
correct = '#2e3125'
error = '#db0030'
hint = '#363a34'
cancel = '#db0030'
gradient_color = ['#d0d0c8', "#494a42"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#d0d0c8'
file_panel_top_path = '#494a42'
file_panel_item_selected_fg = '#494a42'
file_panel_item_selected_bg = '#d0d0c8'

# ========= Sidebar Special Items =========
sidebar_title = '#242424'
sidebar_item_selected_fg = '#494a42'
sidebar_item_selected_bg = '#d0d0c8'
sidebar_divider = '#383835'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#db0030'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#2e3125'
